package com.pokemon.pokemonrpg.model;

public enum Attack {
    // Definindo os ataques com o novo parâmetro: Categoria
    POUND("Pound", 40, Types.NORMAL, DamageCategory.PHYSICAL),
    KARATE_CHOP("Karate Chop", 50, Types.FIGHTING, DamageCategory.PHYSICAL),
    DOUBLE_SLAP("Double Slap", 15, Types.NORMAL, DamageCategory.PHYSICAL),
    COMET_PUNCH("Comet Punch", 18, Types.NORMAL, DamageCategory.PHYSICAL),
    MEGA_PUNCH("Mega Punch", 80, Types.NORMAL, DamageCategory.PHYSICAL),
    PAY_DAY("Pay Day", 40, Types.NORMAL, DamageCategory.PHYSICAL),
    FIRE_PUNCH("Fire Punch", 75, Types.FIRE, DamageCategory.PHYSICAL),
    ICE_PUNCH("Ice Punch", 75, Types.ICE, DamageCategory.PHYSICAL),
    THUNDERPUNCH("Thunderpunch", 75, Types.ELECTRIC, DamageCategory.PHYSICAL),
    SCRATCH("Scratch", 40, Types.NORMAL, DamageCategory.PHYSICAL),
    VICEGRIP("Vicegrip", 55, Types.NORMAL, DamageCategory.PHYSICAL),
    GUILLOTINE("Guillotine", 0, Types.NORMAL, DamageCategory.STATUS),
    RAZOR_WIND("Razor Wind", 80, Types.FLYING, DamageCategory.SPECIAL),
    SWORDS_DANCE("Swords Dance", 0, Types.NORMAL, DamageCategory.STATUS),
    CUT("Cut", 50, Types.NORMAL, DamageCategory.PHYSICAL),
    GUST("Gust", 40, Types.FLYING, DamageCategory.SPECIAL),
    WING_ATTACK("Wing Attack", 35, Types.FLYING, DamageCategory.PHYSICAL),
    WHIRLWIND("Whirlwind", 0, Types.NORMAL, DamageCategory.STATUS),
    FLY("Fly", 70, Types.FLYING, DamageCategory.PHYSICAL),
    BIND("Bind", 15, Types.NORMAL, DamageCategory.PHYSICAL),
    SLAM("Slam", 80, Types.NORMAL, DamageCategory.PHYSICAL),
    VINE_WHIP("Vine Whip", 35, Types.GRASS, DamageCategory.PHYSICAL),
    STOMP("Stomp", 65, Types.NORMAL, DamageCategory.PHYSICAL),
    DOUBLE_KICK("Double Kick", 30, Types.FIGHTING, DamageCategory.PHYSICAL),
    MEGA_KICK("Mega Kick", 120, Types.NORMAL, DamageCategory.PHYSICAL),
    JUMP_KICK("Jump Kick", 70, Types.FIGHTING, DamageCategory.PHYSICAL),
    ROLLING_KICK("Rolling Kick", 60, Types.FIGHTING, DamageCategory.PHYSICAL),
    SAND_ATTACK("Sand-attack", 0, Types.GROUND, DamageCategory.STATUS),
    HEADBUTT("Headbutt", 70, Types.NORMAL, DamageCategory.PHYSICAL),
    HORN_ATTACK("Horn Attack", 65, Types.NORMAL, DamageCategory.PHYSICAL),
    FURY_ATTACK("Fury Attack", 15, Types.NORMAL, DamageCategory.PHYSICAL),
    HORN_DRILL("Horn Drill", 0, Types.NORMAL, DamageCategory.STATUS),
    TACKLE("Tackle", 35, Types.NORMAL, DamageCategory.PHYSICAL),
    BODY_SLAM("Body Slam", 85, Types.NORMAL, DamageCategory.PHYSICAL),
    WRAP("Wrap", 15, Types.NORMAL, DamageCategory.PHYSICAL),
    TAKE_DOWN("Take Down", 90, Types.NORMAL, DamageCategory.PHYSICAL),
    THRASH("Thrash", 90, Types.NORMAL, DamageCategory.PHYSICAL),
    DOUBLE_EDGE("Double-edge", 100, Types.NORMAL, DamageCategory.PHYSICAL),
    TAIL_WHIP("Tail Whip", 0, Types.NORMAL, DamageCategory.STATUS),
    POISON_STING("Poison Sting", 15, Types.POISON, DamageCategory.PHYSICAL),
    TWINEEDLE("Twineedle", 25, Types.BUG, DamageCategory.PHYSICAL),
    PIN_MISSILE("Pin Missile", 14, Types.BUG, DamageCategory.PHYSICAL),
    LEER("Leer", 0, Types.NORMAL, DamageCategory.STATUS),
    BITE("Bite", 60, Types.NORMAL, DamageCategory.PHYSICAL),
    GROWL("Growl", 0, Types.NORMAL, DamageCategory.STATUS),
    ROAR("Roar", 0, Types.NORMAL, DamageCategory.STATUS),
    SING("Sing", 0, Types.NORMAL, DamageCategory.STATUS),
    SUPERSONIC("Supersonic", 0, Types.NORMAL, DamageCategory.STATUS),
    SONICBOOM("Sonicboom", 0, Types.NORMAL, DamageCategory.SPECIAL),
    DISABLE("Disable", 0, Types.NORMAL, DamageCategory.STATUS),
    ACID("Acid", 40, Types.POISON, DamageCategory.SPECIAL),
    EMBER("Ember", 40, Types.FIRE, DamageCategory.SPECIAL),
    FLAMETHROWER("Flamethrower", 95, Types.FIRE, DamageCategory.SPECIAL),
    MIST("Mist", 0, Types.ICE, DamageCategory.STATUS),
    WATER_GUN("Water Gun", 40, Types.WATER, DamageCategory.SPECIAL),
    HYDRO_PUMP("Hydro Pump", 120, Types.WATER, DamageCategory.SPECIAL),
    SURF("Surf", 95, Types.WATER, DamageCategory.SPECIAL),
    ICE_BEAM("Ice Beam", 95, Types.ICE, DamageCategory.SPECIAL),
    BLIZZARD("Blizzard", 120, Types.ICE, DamageCategory.SPECIAL),
    PSYBEAM("Psybeam", 65, Types.PSYCHIC, DamageCategory.SPECIAL),
    BUBBLEBEAM("Bubblebeam", 65, Types.WATER, DamageCategory.SPECIAL),
    AURORA_BEAM("Aurora Beam", 65, Types.ICE, DamageCategory.SPECIAL),
    HYPER_BEAM("Hyper Beam", 150, Types.NORMAL, DamageCategory.SPECIAL),
    PECK("Peck", 35, Types.FLYING, DamageCategory.PHYSICAL),
    DRILL_PECK("Drill Peck", 80, Types.FLYING, DamageCategory.PHYSICAL),
    SUBMISSION("Submission", 80, Types.FIGHTING, DamageCategory.PHYSICAL),
    LOW_KICK("Low Kick", 50, Types.FIGHTING, DamageCategory.PHYSICAL),
    COUNTER("Counter", 0, Types.FIGHTING, DamageCategory.PHYSICAL),
    SEISMIC_TOSS("Seismic Toss", 0, Types.FIGHTING, DamageCategory.PHYSICAL),
    STRENGTH("Strength", 80, Types.NORMAL, DamageCategory.PHYSICAL),
    ABSORB("Absorb", 20, Types.GRASS, DamageCategory.SPECIAL),
    MEGA_DRAIN("Mega Drain", 40, Types.GRASS, DamageCategory.SPECIAL),
    LEECH_SEED("Leech Seed", 0, Types.GRASS, DamageCategory.STATUS),
    GROWTH("Growth", 0, Types.NORMAL, DamageCategory.STATUS),
    RAZOR_LEAF("Razor Leaf", 55, Types.GRASS, DamageCategory.PHYSICAL),
    SOLARBEAM("Solarbeam", 120, Types.GRASS, DamageCategory.SPECIAL),
    POISONPOWDER("Poisonpowder", 0, Types.POISON, DamageCategory.STATUS),
    STUN_SPORE("Stun Spore", 0, Types.GRASS, DamageCategory.STATUS),
    SLEEP_POWDER("Sleep Powder", 0, Types.GRASS, DamageCategory.STATUS),
    PETAL_DANCE("Petal Dance", 70, Types.GRASS, DamageCategory.SPECIAL),
    STRING_SHOT("String Shot", 0, Types.BUG, DamageCategory.STATUS),
    DRAGON_RAGE("Dragon Rage", 0, Types.DRAGON, DamageCategory.SPECIAL),
    FIRE_SPIN("Fire Spin", 15, Types.FIRE, DamageCategory.SPECIAL),
    THUNDERSHOCK("Thundershock", 40, Types.ELECTRIC, DamageCategory.SPECIAL),
    THUNDERBOLT("Thunderbolt", 95, Types.ELECTRIC, DamageCategory.SPECIAL),
    THUNDER_WAVE("Thunder Wave", 0, Types.ELECTRIC, DamageCategory.STATUS),
    THUNDER("Thunder", 120, Types.ELECTRIC, DamageCategory.SPECIAL),
    ROCK_THROW("Rock Throw", 50, Types.ROCK, DamageCategory.PHYSICAL),
    EARTHQUAKE("Earthquake", 100, Types.GROUND, DamageCategory.PHYSICAL),
    FISSURE("Fissure", 0, Types.GROUND, DamageCategory.PHYSICAL),
    DIG("Dig", 100, Types.GROUND, DamageCategory.PHYSICAL),
    TOXIC("Toxic", 0, Types.POISON, DamageCategory.STATUS),
    CONFUSION("Confusion", 50, Types.PSYCHIC, DamageCategory.SPECIAL),
    PSYCHIC("Psychic", 90, Types.PSYCHIC, DamageCategory.SPECIAL),
    HYPNOSIS("Hypnosis", 0, Types.PSYCHIC, DamageCategory.STATUS),
    MEDITATE("Meditate", 0, Types.PSYCHIC, DamageCategory.STATUS),
    AGILITY("Agility", 0, Types.PSYCHIC, DamageCategory.STATUS),
    QUICK_ATTACK("Quick Attack", 40, Types.NORMAL, DamageCategory.PHYSICAL),
    RAGE("Rage", 20, Types.NORMAL, DamageCategory.PHYSICAL),
    TELEPORT("Teleport", 0, Types.PSYCHIC, DamageCategory.STATUS),
    NIGHT_SHADE("Night Shade", 0, Types.GHOST, DamageCategory.SPECIAL),
    MIMIC("Mimic", 0, Types.NORMAL, DamageCategory.STATUS),
    SCREECH("Screech", 0, Types.NORMAL, DamageCategory.STATUS),
    DOUBLE_TEAM("Double Team", 0, Types.NORMAL, DamageCategory.STATUS),
    RECOVER("Recover", 0, Types.NORMAL, DamageCategory.STATUS),
    HARDEN("Harden", 0, Types.NORMAL, DamageCategory.STATUS),
    MINIMIZE("Minimize", 0, Types.NORMAL, DamageCategory.STATUS),
    SMOKESCREEN("Smokescreen", 0, Types.NORMAL, DamageCategory.STATUS),
    CONFUSE_RAY("Confuse Ray", 0, Types.GHOST, DamageCategory.STATUS),
    WITHDRAW("Withdraw", 0, Types.WATER, DamageCategory.STATUS),
    DEFENSE_CURL("Defense Curl", 0, Types.NORMAL, DamageCategory.STATUS),
    BARRIER("Barrier", 0, Types.PSYCHIC, DamageCategory.STATUS),
    LIGHT_SCREEN("Light Screen", 0, Types.PSYCHIC, DamageCategory.STATUS),
    HAZE("Haze", 0, Types.ICE, DamageCategory.STATUS),
    REFLECT("Reflect", 0, Types.PSYCHIC, DamageCategory.STATUS),
    FOCUS_ENERGY("Focus Energy", 0, Types.NORMAL, DamageCategory.STATUS),
    BIDE("Bide", 0, Types.NORMAL, DamageCategory.PHYSICAL),
    METRONOME("Metronome", 0, Types.NORMAL, DamageCategory.STATUS),
    MIRROR_MOVE("Mirror Move", 0, Types.FLYING, DamageCategory.STATUS),
    SELFDESTRUCT("Selfdestruct", 130, Types.NORMAL, DamageCategory.PHYSICAL),
    EGG_BOMB("Egg Bomb", 100, Types.NORMAL, DamageCategory.PHYSICAL),
    LICK("Lick", 20, Types.GHOST, DamageCategory.PHYSICAL),
    SMOG("Smog", 20, Types.POISON, DamageCategory.SPECIAL),
    SLUDGE("Sludge", 65, Types.POISON, DamageCategory.SPECIAL),
    BONE_CLUB("Bone Club", 65, Types.GROUND, DamageCategory.PHYSICAL),
    FIRE_BLAST("Fire Blast", 120, Types.FIRE, DamageCategory.SPECIAL),
    WATERFALL("Waterfall", 80, Types.WATER, DamageCategory.PHYSICAL),
    CLAMP("Clamp", 35, Types.WATER, DamageCategory.PHYSICAL),
    SWIFT("Swift", 60, Types.NORMAL, DamageCategory.SPECIAL),
    SKULL_BASH("Skull Bash", 100, Types.NORMAL, DamageCategory.PHYSICAL),
    SPIKE_CANNON("Spike Cannon", 20, Types.NORMAL, DamageCategory.PHYSICAL),
    CONSTRICT("Constrict", 10, Types.NORMAL, DamageCategory.PHYSICAL),
    AMNESIA("Amnesia", 0, Types.PSYCHIC, DamageCategory.STATUS),
    KINESIS("Kinesis", 0, Types.PSYCHIC, DamageCategory.STATUS),
    SOFTBOILED("Softboiled", 0, Types.NORMAL, DamageCategory.STATUS),
    HI_JUMP_KICK("Hi Jump Kick", 85, Types.FIGHTING, DamageCategory.PHYSICAL),
    GLARE("Glare", 0, Types.NORMAL, DamageCategory.STATUS),
    DREAM_EATER("Dream Eater", 100, Types.PSYCHIC, DamageCategory.SPECIAL),
    POISON_GAS("Poison Gas", 0, Types.POISON, DamageCategory.STATUS),
    BARRAGE("Barrage", 15, Types.NORMAL, DamageCategory.PHYSICAL),
    LEECH_LIFE("Leech Life", 20, Types.BUG, DamageCategory.PHYSICAL),
    LOVELY_KISS("Lovely Kiss", 0, Types.NORMAL, DamageCategory.STATUS),
    SKY_ATTACK("Sky Attack", 140, Types.FLYING, DamageCategory.PHYSICAL),
    TRANSFORM("Transform", 0, Types.NORMAL, DamageCategory.STATUS),
    BUBBLE("Bubble", 20, Types.WATER, DamageCategory.SPECIAL),
    DIZZY_PUNCH("Dizzy Punch", 70, Types.NORMAL, DamageCategory.PHYSICAL),
    SPORE("Spore", 0, Types.GRASS, DamageCategory.STATUS),
    FLASH("Flash", 0, Types.NORMAL, DamageCategory.STATUS),
    PSYWAVE("Psywave", 0, Types.PSYCHIC, DamageCategory.SPECIAL),
    SPLASH("Splash", 0, Types.NORMAL, DamageCategory.STATUS),
    ACID_ARMOR("Acid Armor", 0, Types.POISON, DamageCategory.STATUS),
    CRABHAMMER("Crabhammer", 90, Types.WATER, DamageCategory.PHYSICAL),
    EXPLOSION("Explosion", 170, Types.NORMAL, DamageCategory.PHYSICAL),
    FURY_SWIPES("Fury Swipes", 18, Types.NORMAL, DamageCategory.PHYSICAL),
    BONEMERANG("Bonemerang", 50, Types.GROUND, DamageCategory.PHYSICAL),
    REST("Rest", 0, Types.PSYCHIC, DamageCategory.STATUS),
    ROCK_SLIDE("Rock Slide", 75, Types.ROCK, DamageCategory.PHYSICAL),
    HYPER_FANG("Hyper Fang", 80, Types.NORMAL, DamageCategory.PHYSICAL),
    SHARPEN("Sharpen", 0, Types.NORMAL, DamageCategory.STATUS),
    CONVERSION("Conversion", 0, Types.NORMAL, DamageCategory.STATUS),
    TRI_ATTACK("Tri Attack", 80, Types.NORMAL, DamageCategory.SPECIAL),
    SUPER_FANG("Super Fang", 0, Types.NORMAL, DamageCategory.PHYSICAL),
    SLASH("Slash", 70, Types.NORMAL, DamageCategory.PHYSICAL),
    SUBSTITUTE("Substitute", 0, Types.NORMAL, DamageCategory.STATUS),
    STRUGGLE("Struggle", 50, Types.NORMAL, DamageCategory.PHYSICAL);

    private final String name;
    private final int power;
    private final Types type;
    private final DamageCategory category; // Novo campo

    Attack(String name, int power, Types type, DamageCategory category) {
        this.name = name;
        this.power = power;
        this.type = type;
        this.category = category;
    }

    public String getName() { return name; }
    public int getPower() { return power; }
    public Types getType() { return type; }
    public DamageCategory getCategory() { return category; }
}