spring.datasource.url=jdbc:sqlite:pokemon.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# MUITO IMPORTANTE: 'none' garante que o Spring não vai tentar apagar ou alterar suas tabelas prontas
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true