spring.datasource.url=jdbc:sqlite::memory:
spring.datasource.driver-class-name=org.sqlite.JDBC

# Open connection to the port during testing.
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.pool-name=TestPool

# Create table automatically mirrored
spring.jpa.hibernate.ddl-auto=update


# Offline banner to Spring
spring.main.banner-mode=off 